# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: domraeholiday
# email: dominicgangx@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  One couple's brave attempt at a pretentious travelogue.
baseurl: "" # the subpath of your site, e.g. /blog
banner_title: udomraemen
banner_subtitle: > 
 Tokyo!
banner_image: "http://im.vsco.co/1/51f48bb095e8247120/56c9e77a40955b61337b8a75/vsco_022216.jpg"
url: "http://domrae.github.io" # the base hostname & protocol for your site
instagram_username_1: dommmm
instagram_username_2: dznrachel
copyright_statement: >
 All Rights Reserved &#169; Copyright 2016, Dominic Gan & Rachel Chen. Icons courtesy of <a href="http://www.freepik.com" title="Freepik" target="_blank">Freepik</a> (<a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>)
# github_username:  domrae

# Build settings
markdown: kramdown
